### ISSUE TITLE
Credits?

### ISSUE THREAD

**Issue by Defman21** [babobski/Deep-focus-color-schemes#1]
Soda Dark, Monokai (both versions) and Flasty are my color schemes and if you have changed them - please add credits somewhere referring to the original ones (or at least to me). Thanks :)
Regardless, awesome work :)

**Comment by babobski** [comment]
:blush: Yes youre wright, some credits are needed. 
Just grabed some color schemes i wanted to adapt for my skin, changed the background, folding margins etc. to match the skin. But forgot to credit the people that did all the hard work.
But to rectify my mistake, the credits are added :)

**Comment by Defman21** [comment]
Thank you :+1:
